### ISSUE TITLE
Support multiple partitions

### ISSUE THREAD

**Issue by skoppar** [ippontech/spark-kafka-source#2]
Hi, 
I am not sure if this is of interest to all, but it seems to be a general purpose solution. From what I saw while using this library, it does not support multiple partitions. I modified the code to support multiple partitions (and multiple topics)  and am willing to submit a PR if that is desirable. Also, before submitting the PR, I wanted to make sure I have not missed out any usage pattern which provides multi partition capability. Attaching the file with the changes. Some of the references are to the files in my code base. If and when I submit the PR, I will make the required modifications
[ZookeeperOffsetStore_MultiPartition.txt](https://github.com/ippontech/spark-kafka-source/files/559328/ZookeeperOffsetStore_MultiPartition.txt)

Disclaimer: I have tested this for single topic with multiple partitions. Not for multiple topics.

**Comment by aseigneurin** [comment]
The code already supports a topic with multiple partitions. The string stored in zookeeper looks like `<partition id>:<offset>,<partition id>:<offset>,...`.

Code related to that functionality is [here](https://github.com/ippontech/spark-kafka-source/blob/master/src/main/scala/com/ippontech/kafka/stores/ZooKeeperOffsetsStore.scala#L56) and [here](https://github.com/ippontech/spark-kafka-source/blob/master/src/main/scala/com/ippontech/kafka/stores/ZooKeeperOffsetsStore.scala#L27).

You can see an example on [my blog post](http://aseigneurin.github.io/2016/05/07/spark-kafka-achieving-zero-data-loss.html):

```
2016-05-04 14:12:29,842 DEBUG - Read offset ranges: 0:38114984,1:38115057
```

**Comment by skoppar** [comment]
Can you share a sample implementation in that case, like a unit test? May be I did not use it right. It did store multiple offsets the first time, i.e when it started with createDirectStream without prior entries in ZK, but on readOffsets it did not retrieve all the offsets and further processing just kept accessing 1 partition. May be I missed something.

**Comment by skoppar** [comment]
Also, thanks a lot for the blog and your idea of using ZK for offset storing. It is very helpful

**Comment by skoppar** [comment]
The challenge I had was that, I had to specify the complete path including the partition as zkPath
Something like this:
val offsetsStore = new ZooKeeperOffsetsStore(conf.getString("zkHosts"), "/consumers/topics/"+ topics + "/0")
Is this not required? 
Your usage might be having some API to send that for all partitions, in to this method.

**Comment by aseigneurin** [comment]
Oh, I see what's wrong: you're specifying the path where Kafka writes its own offsets so you're overwriting what Kafka is writing.

Instead, specify a totally different path. In my case, I use "appname/offsets". This is enough since my app is reading from a single topic.

If the path does not exist, the code will create it when saving for the first time.

**Comment by skoppar** [comment]
I see. But I have no other consumers so no offsets were being written to ZK
anyways. Do you think it has any risks the way I am doing it? So far it
seems to be working well for me. And from coding standpoint, it should work
for multiple topics also. Yet to test that bit.
Trying to evaluate which approach is better :)
regards
Sunita

**Comment by aseigneurin** [comment]
Well, no, don't do that, you're messing up with Kafka. Use your own path in ZK.

**Comment by skoppar** [comment]
Ok. Thanks for sharing your knowledge Alexis.. Appreciate it
Also, if you can share a testcase, that might help others like me.
